language: android

jdk:
 - oraclejdk7

before_install:
 - chmod +x gradlew

android:
  components:
    - build-tools-23.0.1
    - android-23
  licenses:
    - android-sdk-license-5be876d5

notifications:
  email: false